apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-willing-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: date
          name: siteStartTime
          label: 建站时间
        - $formkit: text
          name: icp
          label: ICP 备案
          placeholder: 请输入 ICP 备案号
          help: "京ICP备xxxxxxxx号"
        - $formkit: url
          name: postRandomImg
          label: 博客封面随机 API
          validation: "url"
          value: "https://imgapi.xl0408.top/index.php"
          help: "填写随机图Api  例如：https://imgapi.xl0408.top/index.php"
    - group: header
      label: 顶部
      formSchema:
        - $formkit: menuRadio
          name: menuItem
          id: menuItem
          key: menuItem
          label: 导航栏
          value: ""
        - $formkit: radio
          name: moment
          label: 说说模块
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: topName
          label: 名称
          help: "左上角名称，默认为站点名"
        - $formkit: text
          name: topName_after
          label: 下拉标题
          help: "下滑后顶部标题，默认为页面标题"
        - $formkit: repeater
          name: leftList
          label: 导航栏左侧下拉内容
          value: [ ]
          children:
            - $formkit: text
              name: name
              label: 名称，例如：关于
              value: ""
            - $formkit: menuRadio
              name: menu
              label: 选择一个菜单作为列表
              value: ""

    - group: footer
      label: 底部
      formSchema:
        - $formkit: repeater
          name: socials
          label: 社交账号
          value: [ ]
          children:
            - $formkit: text
              name: name
              label: 名称
              value: ""
            - $formkit: text
              name: url
              label: 跳转链接
              value: ""
            - $formkit: text
              name: icon
              label: 格式：<i class="fa-brands fa-github"></i>，查看：fontawesome.com
              value: ""
        - $formkit: repeater
          name: listGroup
          label: 底部链接群
          value: [ ]
          children:
            - $formkit: text
              name: name
              label: 名称，例如：关于
              value: ""
            - $formkit: menuRadio
              name: menu
              label: 选择一个菜单作为列表
              value: ""
        - $formkit: repeater
          name: lowerLink
          label: copyright底部链接
          value: [ ]
          children:
            - $formkit: text
              name: name
              label: 名称，例如：虫洞
              value: ""
            - $formkit: text
              name: url
              label: 跳转链接
              value: ""
    - group: postSetting
      label: 文章
      formSchema:
        - $formkit: repeater
          name: recommend
          label: 首页文章推荐
          value: [ ]
          children:
            - $formkit: postSelect
              name: posts
              label: 选择要推荐的文章(至少两个)
              value: ""
        - $formkit: text
          name: agreementName
          label: 文章协议
          value: "CC BY-NC-SA 4.0"
        - $formkit: text
          name: agreementUrl
          label: 文章协议跳转地址
          value: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

    - group: personal
      label: 个人信息
      formSchema:
        - $formkit: text
          name: qq
          label: QQ号
          help: "用于头像等功能"
        - $formkit: text
          name: nickName
          label: 显示名称
          help: "信息栏显示的名称"
        - $formkit: text
          name: signature
          label: 签名
          help: "名称下面的文字"
        - $formkit: attachment
          name: reward
          label: 打赏码
          help: "文章末尾打赏图片，留空则不显示"
    - group: leftAside
      label: 左侧栏
      formSchema:
        - $formkit: textarea
          name: noticeWidgets
          label: 公告内容
          value: "有问题请直接留言，不方便留言的可以添加QQ和微信。"
        - $formkit: textarea
          name: indexWidgets
          label: 首页左组件
          value: "personal,notice,updates,weibo,comment,tag,archive,information"
          help: "personal(个人信息),notice(公告),updates(最新文章),comment(最新评论),tag(标签云),archive(归档),information(网站资讯),微博热搜(weibo)"
        - $formkit: textarea
          name: postWidgets
          label: 文章左组件
          value: "personal,notice,toc,updates"
          help: "personal(个人信息),toc(目录),updates(最新文章),微博热搜(weibo),可自由组合，用英文逗号隔开"





