apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-willing
spec:
  customTemplates:
    page:
      - name: 友链
        description: 友情链接页
        screenshot:
        file: page_links.html
  displayName: Theme Willing
  author:
    name: halo-dev
    website: "https://halo.run"
  description: Halo 2.0 Theme base on Thymeleaf
  logo: "https://halo.run/logo"
  website: "https://halo.run"
  repo: "https://github.com/halo-sigs/theme-starter"
  settingName: "theme-willing-setting"
  configMapName: "theme-willing-configMap"
  version: "1.0"
  requires: ">=2.0.0"
